// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjgQae4saqyTYWaUE6o18Ujfg88EYYjOc',
    appId: '1:439511784463:web:cb12d685f141e8bcd0977a',
    messagingSenderId: '439511784463',
    projectId: 'weddingplanner-c97cc',
    authDomain: 'weddingplanner-c97cc.firebaseapp.com',
    storageBucket: 'weddingplanner-c97cc.firebasestorage.app',
    measurementId: 'G-5K6HE6CVGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmTn_Vu3CYaOoIaLR0gS1DJ9xKhBKb3WQ',
    appId: '1:439511784463:android:b8ea6d088452c023d0977a',
    messagingSenderId: '439511784463',
    projectId: 'weddingplanner-c97cc',
    storageBucket: 'weddingplanner-c97cc.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJMeiZ7V8q2Q0c40ul7t9ww-Ra0ap3sig',
    appId: '1:439511784463:ios:a473fe71e2a2ba93d0977a',
    messagingSenderId: '439511784463',
    projectId: 'weddingplanner-c97cc',
    storageBucket: 'weddingplanner-c97cc.firebasestorage.app',
    iosBundleId: 'com.chandu.bauer',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJMeiZ7V8q2Q0c40ul7t9ww-Ra0ap3sig',
    appId: '1:439511784463:ios:a473fe71e2a2ba93d0977a',
    messagingSenderId: '439511784463',
    projectId: 'weddingplanner-c97cc',
    storageBucket: 'weddingplanner-c97cc.firebasestorage.app',
    iosBundleId: 'com.chandu.bauer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjgQae4saqyTYWaUE6o18Ujfg88EYYjOc',
    appId: '1:439511784463:web:ab91e9ee215f5619d0977a',
    messagingSenderId: '439511784463',
    projectId: 'weddingplanner-c97cc',
    authDomain: 'weddingplanner-c97cc.firebaseapp.com',
    storageBucket: 'weddingplanner-c97cc.firebasestorage.app',
    measurementId: 'G-V65C3Z9ENP',
  );

}